stages:
  prepare:
    cmd: python src/prepare.py
    deps:
      - src/prepare.py
      - params.yaml
      - data/raw/heart_failure_clinical_records.csv
    outs:
      - data/processed/

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - params.yaml
      - data/processed/
    params:
      - train.model_params
    outs:
      - model.json