prepare:
  test_size: 0.2
  random_state: 42

train:
  model_params:
    n_estimators: 1000
    max_depth: 5
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8
    reg_alpha: 0.1
    reg_lambda: 1.0